name: first workflow

on:
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest  
    steps:
      - name: log test message
        run: echo "This is a test message for the workflow"
        
      - name: checkout
        uses: actions/checkout@v4.2.2
        
      - name: list repo files
        run: ls -la
        
      - name: use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: install dependencies
        run: npm install
        
      - name: run tests
        run: npm run test
