name: first workflow

on:
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest  
    steps:
      - name: log test message
        run: echo "This is a test message for the workflow"
